# I have installed the AWSCLI and entered my AWS_Access_key and AWS_secret_key to authorize access on my local machine.
# I have created a security group to allow tcp connections through port 22 and 80
# I'm spinning up a linux EC2 instance on my AWS account

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: security group
    ec2_group:
      name: Ansible
      description: Security Group
      region: us-west-2
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: firewall
  - name: Provision a set of instances
    ec2:
      key_name: Ansible_AWS
      region: us-west-2                          # Region of Instance
      instance_type: t2.micro                    # Instance-type
      vpc_subnet_id: subnet-11027e76             # This is my default-vpc subnet ID
      image: ami-2ffa634f                        # This is an image which I created
      assign_public_ip: yes
      group: Ansible
      wait: true
      exact_count: 1
      count_tag:
        Name: Demo
      instance_tags:
        Name: Demo
    register: ec2





